obj-$(CONFIG_MHI_BUS) += mhi.o
mhi-y := init.o main.o pm.o boot.o
mhi-$(CONFIG_MHI_BUS_DEBUG) += debugfs.o

obj-$(CONFIG_MHI_BUS_PCI_GENERIC) += mhi_pci_generic.o
mhi_pci_generic-y += pci_generic.o

obj-$(CONFIG_MHI_SAHARA_DIAG) += mhi_sahara_diag.o
mhi_sahara_diag-y += sahara_diag.o
